import mongoose, { Document, Schema } from 'mongoose';

// ---------------------------------------------------------------------------
// Animation — an ordered set of pixel-art frames generated by PixelLab from a
// source sprite + action text. Frames are stored as individual PNG objects in
// S3 (frameKeys, ordered) so delete/reorder/edit stay cheap; spritesheet/GIF
// exports are materialized on demand and their keys cached on the doc.
// ---------------------------------------------------------------------------

export type AnimationStatus = 'generating' | 'ready' | 'failed';

export interface IAnimation extends Document {
  _id: mongoose.Types.ObjectId;
  ownerId: string;
  projectId: string;
  name: string;
  action: string;             // last generation/edit text
  spriteId: string;           // source Sprite doc ('' when generated from a raw key)
  characterId: string;        // linked Character ('' when unattached)
  sourceImageKey: string;     // S3 key of the first-frame source image
  frameKeys: string[];        // ordered S3 keys, one PNG per frame
  frameWidth: number;
  frameHeight: number;
  fps: number;
  loop: boolean;
  spritesheetKey: string;     // export cache ('' until exported)
  spritesheetJsonKey: string;
  gifKey: string;
  status: AnimationStatus;
  statusError: string;
  createdAt: Date;
  updatedAt: Date;
}

const AnimationSchema = new Schema<IAnimation>(
  {
    ownerId:            { type: String, required: true, index: true },
    projectId:          { type: String, required: true, index: true },
    name:               { type: String, required: true },
    action:             { type: String, default: '' },
    spriteId:           { type: String, default: '', index: true },
    characterId:        { type: String, default: '', index: true },
    sourceImageKey:     { type: String, required: true },
    frameKeys:          { type: [String], default: [] },
    frameWidth:         { type: Number, default: 0 },
    frameHeight:        { type: Number, default: 0 },
    fps:                { type: Number, default: 8 },
    loop:               { type: Boolean, default: true },
    spritesheetKey:     { type: String, default: '' },
    spritesheetJsonKey: { type: String, default: '' },
    gifKey:             { type: String, default: '' },
    status:             { type: String, enum: ['generating', 'ready', 'failed'], default: 'generating' },
    statusError:        { type: String, default: '' },
  },
  { timestamps: true },
);

const AnimationModel = mongoose.model<IAnimation>('Animation', AnimationSchema);
export default AnimationModel;
