import { CanonicalExport, ExportFile, FormatModule } from '../types';

const TYPE_DEFINITIONS = `// QuestFlow — TypeScript type definitions (generated by QuestFlow)

export type Rarity = 'common' | 'rare' | 'epic';

export interface QuestMeta {
  id: string;
  title: string;
  genre: string;
  description: string;
  startNodeId: string;
}

export interface QuestEdge {
  id: string;
  source: string;
  target: string;
}

export interface Quest {
  id: string;
  variant: string;
  title: string;
  body: string;
  npcIds: string[];
  monsterIds: string[];
  rewardIds: string[];
}

export interface Character {
  id: string;
  name: string;
  appearance: string;
  background: string;
  imageUrl: string;
}

export interface Reward {
  id: string;
  title: string;
  description: string;
  rarity: Rarity;
  imageUrl: string;
}

export interface Objective {
  id: string;
  title: string;
  description: string;
}

export interface Questline {
  meta: QuestMeta;
  questIds: string[];
  edges: QuestEdge[];
}
`;

function readme(title: string): string {
  return `# QuestFlow JSON Export — ${title}

## Files
| File | Description |
|---|---|
| questline.json | Root file: meta, quest ID list, edges |
| quests/quest_N.json | One file per quest node |
| characters.json | Shared character definitions |
| rewards.json | Shared reward definitions |
| objectives.json | Questline objectives |
| questline.d.ts | TypeScript type definitions |

## Usage (TypeScript)
\`\`\`typescript
import type { Questline, Quest, Character, Reward } from './questline.d.ts';
import * as fs from 'fs';

const questline: Questline = JSON.parse(fs.readFileSync('questline.json', 'utf8'));
const quests: Quest[] = questline.questIds.map(id =>
  JSON.parse(fs.readFileSync(\`quests/\${id}.json\`, 'utf8'))
);
const characters: Character[] = JSON.parse(fs.readFileSync('characters.json', 'utf8'));
const rewards: Reward[] = JSON.parse(fs.readFileSync('rewards.json', 'utf8'));

// Start the quest at:
const startQuest = quests.find(q => q.id === questline.meta.startNodeId);
\`\`\`
`;
}

function render(payload: CanonicalExport): ExportFile[] {
  const files: ExportFile[] = [];

  files.push({
    path: 'questline.json',
    content: JSON.stringify({
      meta:     payload.meta,
      questIds: payload.nodes.map((n) => n.id),
      edges:    payload.edges,
    }, null, 2),
  });

  for (const node of payload.nodes) {
    files.push({ path: `quests/${node.id}.json`, content: JSON.stringify(node, null, 2) });
  }

  files.push({ path: 'characters.json', content: JSON.stringify(payload.characters, null, 2) });
  files.push({ path: 'rewards.json',    content: JSON.stringify(payload.rewards,    null, 2) });
  files.push({ path: 'objectives.json', content: JSON.stringify(payload.objectives, null, 2) });
  files.push({ path: 'questline.d.ts',  content: TYPE_DEFINITIONS });
  files.push({ path: 'README.md',       content: readme(payload.meta.title) });

  return files;
}

export default {
  id:        'questflow-json',
  label:     'QuestFlow JSON',
  extension: 'zip',
  mimeType:  'application/zip',
  render,
} as FormatModule;
